# Generated by Django 3.0.4 on 2020-04-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteviewer', '0002_comment_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
