# Generated by Django 3.0.4 on 2020-04-05 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('siteviewer', '0005_auto_20200405_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='url')),
                ('summary', models.TextField(db_index=True, max_length=200, verbose_name='summary')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 4, 5, 12, 39, 8, 55628, tzinfo=utc), verbose_name='Date')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
