# Generated by Django 3.0.5 on 2020-04-15 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('siteviewer', '0007_auto_20200405_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 12, 53, 16, 574771, tzinfo=utc), verbose_name='Date'),
        ),
    ]
