# Generated by Django 3.0.5 on 2020-04-19 16:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('siteviewer', '0008_auto_20200415_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 16, 21, 58, 918745, tzinfo=utc), verbose_name='Date'),
        ),
    ]
