# Generated by Django 3.0.5 on 2020-04-25 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('siteviewer', '0011_auto_20200423_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 15, 30, 44, 549009, tzinfo=utc), verbose_name='Date'),
        ),
    ]
