# Generated by Django 3.0.5 on 2020-04-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteviewer', '0012_auto_20200425_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
