# Generated by Django 3.0.5 on 2020-05-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteviewer', '0014_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
